### ISSUE TITLE
Blog name at top of post won't link back to the home page

### ISSUE THREAD

**Issue by kekearif** [AWEEKJ/aweekj.github.io#9]
Hey. Having an issue. If I go to a blog post and then tap the name of the blog "Keke Arif" it just displays the same post and doesn't link to the home screen. On other pages though such as about it does link back to the home screen. Any ideas what I might be doing wrong? http://kekearif.github.io

**Comment by AWEEKJ** [comment]
Thanks for the issue and I fixed this just before. Please check differences [here](https://github.com/AWEEKJ/Kiko-plus/commit/c9900407d39bdb9163445ecd07af6af2105f4f68).

**Comment by kekearif** [comment]
Awesome! Working great now. Thanks :)
